// Package sanr wires the generated Sanr API client (gen.go) to the shared httpx
// engine and injects bearer-token auth. gen.go is regenerated by `task gen`;
// this hand-written file is never overwritten.
package sanr

import (
	"context"
	"net/http"

	"santiment.net/san-skills/internal/platform/config"
	"santiment.net/san-skills/internal/platform/httpx"
)

// Backend is the logical name used in errors and diagnostics.
const Backend = "sanr"

// New builds a typed Sanr client bound to the resolved settings. The bearer
// token (if any) is attached to every request via a request editor.
func New(s *config.Settings, opts httpx.Options) (*ClientWithResponses, error) {
	doer := httpx.New(opts)
	editor := func(_ context.Context, req *http.Request) error {
		if s.SanrToken != "" && req.Header.Get("Authorization") == "" {
			req.Header.Set("Authorization", "Bearer "+s.SanrToken)
		}
		return nil
	}
	return NewClientWithResponses(s.SanrBaseURL,
		WithHTTPClient(doer),
		WithRequestEditorFn(editor),
	)
}
