// Package arena wires the generated Arena API client (gen.go) to the shared
// httpx engine and injects x-api-key auth. gen.go is regenerated by `task gen`;
// this hand-written file is never overwritten.
package arena

import (
	"context"
	"net/http"

	"santiment.net/san-skills/internal/platform/config"
	"santiment.net/san-skills/internal/platform/httpx"
)

// Backend is the logical name used in errors and diagnostics.
const Backend = "arena"

// New builds a typed Arena client bound to the resolved settings. The API key
// (if any) is attached to every request via the x-api-key header.
func New(s *config.Settings, opts httpx.Options) (*ClientWithResponses, error) {
	doer := httpx.New(opts)
	editor := func(_ context.Context, req *http.Request) error {
		if s.ArenaAPIKey != "" && req.Header.Get("x-api-key") == "" {
			req.Header.Set("x-api-key", s.ArenaAPIKey)
		}
		return nil
	}
	return NewClientWithResponses(s.ArenaBaseURL,
		WithHTTPClient(doer),
		WithRequestEditorFn(editor),
	)
}
