// Package httpx is the shared HTTP engine for every CLI in the family.
// It implements the request-doer interface expected by oapi-codegen generated
// clients (a Do(*http.Request) method) and adds timeouts, bounded retries with
// backoff on 429/5xx, and a stable User-Agent.
package httpx

import (
	"fmt"
	"io"
	"math"
	"net/http"
	"time"
)

// Doer is the minimal HTTP interface; *http.Client and *Client both satisfy it,
// and it matches the HttpRequestDoer interface generated by oapi-codegen.
type Doer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Options configures a Client.
type Options struct {
	// Timeout is the per-attempt request timeout. Zero means 30s.
	Timeout time.Duration
	// MaxRetries is the number of retries after the first attempt. Zero means 2.
	MaxRetries int
	// UserAgent is sent on every request.
	UserAgent string
	// Transport overrides the underlying RoundTripper (tests inject here).
	Transport http.RoundTripper
}

// Client is a retrying HTTP client. It is safe for concurrent use.
type Client struct {
	http       *http.Client
	maxRetries int
	userAgent  string
}

// New builds a Client from Options, applying defaults for zero values.
func New(opts Options) *Client {
	if opts.Timeout == 0 {
		opts.Timeout = 30 * time.Second
	}
	if opts.MaxRetries == 0 {
		opts.MaxRetries = 2
	}
	if opts.UserAgent == "" {
		opts.UserAgent = "san-skills-cli"
	}
	return &Client{
		http:       &http.Client{Timeout: opts.Timeout, Transport: opts.Transport},
		maxRetries: opts.MaxRetries,
		userAgent:  opts.UserAgent,
	}
}

// Do executes the request with retries on transient failures (429 and 5xx).
// Retries are only attempted when the request body can be replayed.
func (c *Client) Do(req *http.Request) (*http.Response, error) {
	if req.Header.Get("User-Agent") == "" {
		req.Header.Set("User-Agent", c.userAgent)
	}

	var lastErr error
	for attempt := 0; attempt <= c.maxRetries; attempt++ {
		if attempt > 0 {
			if err := sleepBackoff(req, attempt); err != nil {
				return nil, err
			}
			if req.GetBody != nil {
				body, err := req.GetBody()
				if err != nil {
					return nil, fmt.Errorf("replay request body: %w", err)
				}
				req.Body = body
			}
		}

		resp, err := c.http.Do(req)
		if err != nil {
			lastErr = err
			if req.GetBody == nil && req.Body != nil {
				return nil, err // cannot safely retry a consumed body
			}
			continue
		}
		if !shouldRetry(resp.StatusCode) || attempt == c.maxRetries {
			return resp, nil
		}
		// Drain and close so the connection can be reused before retrying.
		_, _ = io.Copy(io.Discard, resp.Body)
		_ = resp.Body.Close()
		lastErr = fmt.Errorf("server returned %d", resp.StatusCode)
	}
	return nil, lastErr
}

func shouldRetry(status int) bool {
	return status == http.StatusTooManyRequests || status >= 500
}

// sleepBackoff waits with exponential backoff, respecting the request context.
func sleepBackoff(req *http.Request, attempt int) error {
	delay := time.Duration(math.Pow(2, float64(attempt-1))) * 250 * time.Millisecond
	timer := time.NewTimer(delay)
	defer timer.Stop()
	select {
	case <-req.Context().Done():
		return req.Context().Err()
	case <-timer.C:
		return nil
	}
}
